### ISSUE TITLE
Добавить файл логирования

### ISSUE THREAD

**Issue by sheepsupremacy** [st054745/RCA#4]

**Comment by danila19991** [comment]
посмотреть функцию qInstallMessageHandler

зависимость от уровня.
debug время выполнения функции + дополнительная информация необходимая для отслеживания выполнения программы
info создание объектов, вход в функцию(+ параметры)
warning поведение которого быть не должно, но ты знаешь как это обрабатывать(нет нужного cu)
critical ты не можешь продолжать работать корректно, но можешь само починиться возможно потеряв часть информации
fatal не исправимая ошибка 

в сообщении лога показывать информацию, время его вознискновения с точностью до наносекунды и указывать часовой пояс + тело сообщения

сделать возможность записи в файл, записи в файл в зависимости от уровня и вывода в консоль

**Comment by danila19991** [comment]
предусмотреть возможность записи догов в сокет и отправка сообщений при помощи http

**Comment by sheepsupremacy** [comment]
Файл логирования добавлен. Вопрос решен не полностью, но хватает для текущего этапа. По соответствующим оставшимся проблемам созданы новые issues.
